name: Automated Python Script Execution on Push
on: [push]

jobs:
  test_all:
    name: Check Lowest Number Python Script Outputs Match Expected
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Test 10 Numbers
        continue-on-error: true
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
          diff test_data/test1_expected.txt test_data/test1_actual.txt
      
      - name: Test 1 Number
        continue-on-error: true
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt
          diff test_data/test2_expected.txt test_data/test2_actual.txt
      
      - name: Test Blank File
        continue-on-error: true
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt
          diff test_data/test3_expected.txt test_data/test3_actual.txt
